# Generated by Django 5.2.3 on 2025-06-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_override', models.IntegerField(blank=True, null=True)),
                ('monthly_limit_override', models.IntegerField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_used', models.IntegerField()),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('service_used', models.CharField(max_length=50)),
                ('source_language', models.CharField(max_length=10)),
                ('target_languages', models.JSONField(default=list)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.translationtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_date'],
            },
        ),
    ]
