# Generated by Django 5.2.3 on 2025-06-16 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetrequest_userdevice_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
