# Generated by Django 5.2.3 on 2025-06-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdevice_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'ordering': ['-last_used'], 'verbose_name': 'Appareil utilisateur', 'verbose_name_plural': 'Appareils utilisateurs'},
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_fingerprint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
