# Generated by Django 5.2.3 on 2025-06-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='translation_files/')),
                ('file_type', models.CharField(choices=[('po', 'PO File'), ('json', 'JSON File'), ('php', 'PHP File'), ('yaml', 'YAML File'), ('yml', 'YML File'), ('xml', 'XML File'), ('arb', 'ARB File'), ('properties', 'Properties File'), ('csv', 'CSV File'), ('ts', 'TypeScript File')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('translating', 'Translating'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('detected_framework', models.CharField(blank=True, max_length=50)),
                ('encoding', models.CharField(default='utf-8', max_length=50)),
                ('total_strings', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('source_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('is_translated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('is_fuzzy', models.BooleanField(default=False)),
                ('is_plural', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='files.translationfile')),
            ],
            options={
                'ordering': ['line_number', 'key'],
                'unique_together': {('file', 'key')},
            },
        ),
    ]
