# Generated by Django 5.2.3 on 2025-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_translationfile_id_alter_translationstring_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for processing', max_length=255, null=True),
        ),
    ]
