# Generated by Django 5.2.3 on 2025-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_translationstring_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationstring',
            name='task_id',
        ),
        migrations.AddField(
            model_name='translationfile',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for processing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='translationfile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('translating', 'Translating'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', max_length=20),
        ),
    ]
