# Generated by Django 5.2.3 on 2025-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_translationstring_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
    ]
