# Generated by Django 5.2.3 on 2025-06-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_translationstring_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationfile',
            name='file_type',
            field=models.CharField(choices=[('po', 'PO File'), ('json', 'JSON File')], max_length=20),
        ),
    ]
