# Generated by Django 5.2.3 on 2025-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_translationfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfile',
            name='detected_language',
            field=models.CharField(blank=True, help_text='Code de langue détectée automatiquement', max_length=10),
        ),
        migrations.AddField(
            model_name='translationfile',
            name='detected_language_confidence',
            field=models.FloatField(default=0.0, help_text='Confiance de la détection de langue'),
        ),
    ]
