# Generated by Django 5.2.3 on 2025-06-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_translationfile_detected_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationstring',
            name='is_translated',
        ),
    ]
