# Generated by Django 5.2.3 on 2025-06-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_is_translated_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationstring',
            name='translated_text',
        ),
    ]
