# Generated by Django 5.2.3 on 2025-06-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='translationtask',
            name='service',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translation_method',
        ),
        migrations.DeleteModel(
            name='TranslationService',
        ),
    ]
