# Generated by Django 5.2.3 on 2025-06-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('translation_complete', 'Translation Complete'), ('translation_failed', 'Translation Failed'), ('quota_warning', 'Quota Warning'), ('quota_exceeded', 'Quota Exceeded'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system', 'System Notification')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('action_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_translation_complete', models.BooleanField(default=True)),
                ('email_translation_failed', models.BooleanField(default=True)),
                ('email_quota_warnings', models.BooleanField(default=True)),
                ('email_subscription_alerts', models.BooleanField(default=True)),
                ('email_payment_alerts', models.BooleanField(default=True)),
                ('app_translation_complete', models.BooleanField(default=True)),
                ('app_quota_warnings', models.BooleanField(default=True)),
                ('app_system_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
