# Generated by Django 5.2.3 on 2025-06-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('translation_complete', 'Translation Complete'), ('translation_failed', 'Translation Failed'), ('quota_warning', 'Quota Warning'), ('quota_exceeded', 'Quota Exceeded'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_notification', 'System Notification')], max_length=30),
        ),
    ]
